apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-eval-celery-training
  namespace: default
  annotations:
    run.googleapis.com/ingress: none
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
  labels:
    app: ml-eval-platform
    component: celery-training
    env: production
spec:
  template:
    metadata:
      annotations:
        # High resource allocation for ML training
        run.googleapis.com/cpu: "4"
        run.googleapis.com/memory: "8Gi"
        run.googleapis.com/max-instances: "3"
        run.googleapis.com/min-instances: "0"
        
        # GPU support (if available)
        run.googleapis.com/gpu: "1"
        run.googleapis.com/gpu-type: "nvidia-t4"
        
        # Performance optimizations
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/execution-environment: "gen2"
        
        # VPC and database connectivity
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:REGION:ml-eval-db"
        run.googleapis.com/vpc-access-connector: "projects/PROJECT_ID/locations/REGION/connectors/ml-eval-connector"
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
        
        # Long-running training tasks
        run.googleapis.com/timeout: "7200s"
      labels:
        app: ml-eval-platform
        component: celery-training
        env: production
    spec:
      containerConcurrency: 1  # Single task processing
      timeoutSeconds: 7200     # 2 hours for training
      serviceAccountName: ml-eval-celery-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: celery-training
        image: gcr.io/PROJECT_ID/ml-eval-celery:TAG
        command: ["celery"]
        args: ["-A", "src.celery_app", "worker", "--loglevel=info", "--queue=training", "--concurrency=1", "--max-tasks-per-child=1"]
        
        # High resource allocation for ML training
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        
        # Health checks adapted for Celery
        startupProbe:
          exec:
            command: ["celery", "-A", "src.celery_app", "inspect", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
        
        livenessProbe:
          exec:
            command: ["celery", "-A", "src.celery_app", "inspect", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
        
        # Environment variables
        env:
        - name: ENV
          value: "production"
        - name: CELERY_WORKER_TYPE
          value: "training"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ml-eval-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ml-eval-secrets
              key: redis-url
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: C_FORCE_ROOT
          value: "0"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        
        # Volume mounts for model storage
        volumeMounts:
        - name: gcs-fuse
          mountPath: /app/data
          readOnly: false
      
      volumes:
      - name: gcs-fuse
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: false
          volumeAttributes:
            bucketName: "ml-eval-storage-PROJECT_ID"
            mountOptions: "implicit-dirs"
  
  traffic:
  - percent: 100
    latestRevision: true