apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-eval-frontend
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  labels:
    app: ml-eval-platform
    component: frontend
    env: production
spec:
  template:
    metadata:
      annotations:
        # Resource allocation optimized for Next.js
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/max-instances: "20"
        run.googleapis.com/min-instances: "1"
        
        # Performance optimizations
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/execution-environment: "gen2"
        
        # CDN and caching
        run.googleapis.com/description: "ML Evaluation Platform Frontend"
      labels:
        app: ml-eval-platform
        component: frontend
        env: production
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: ml-eval-frontend-sa@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/ml-eval-frontend:TAG
        ports:
        - name: http1
          containerPort: 8080
        
        # Resource allocation
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        
        # Health checks
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
        
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Environment variables
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: NEXT_PUBLIC_API_URL
          value: "https://ml-eval-backend-PROJECT_ID.REGION.run.app"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://ml-eval-backend-PROJECT_ID.REGION.run.app"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
  
  traffic:
  - percent: 100
    latestRevision: true